name: Azure Login with UMI

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  login-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with UMI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY

      - name: Deploy SQL script
        uses: azure/sql-action@v2.3
        with:
          connection-string: "Server=tcp:sabrinserver.database.windows.net;Authentication=Active Directory Managed Identity;Database=test"
          path: './test.sql'
          action: 'sql'
