name: Test Azure Login with UMI

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login with UMI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY

      - name: Show Azure Account Info
        run: az account show

